# Generated by Django 5.0.7 on 2024-08-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_code_service_origin_service_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='main.service'),
            preserve_default=False,
        ),
    ]
