# Generated by Django 5.0.7 on 2024-08-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_code_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codes',
            field=models.ManyToManyField(to='main.code'),
        ),
    ]
