# Generated by Django 5.0.7 on 2024-08-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_originmigrationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='originmigrationtoken',
            name='codes',
            field=models.ManyToManyField(to='main.code'),
        ),
    ]
