# Generated by Django 5.0.7 on 2024-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_originmigrationtoken_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='origin',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
