# Generated by Django 5.0.7 on 2024-09-01 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_group_service_oidc_client_user_sso_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPassword',
            fields=[
                ('password', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='allow_max_configurations',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='userserviceconnection',
            name='configuration_allow_max',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='ServiceConfigurationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('check_regex', models.CharField(max_length=512)),
                ('hidden', models.BooleanField(default=False)),
                ('is_password', models.BooleanField()),
                ('default', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_steps', to='main.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('set_idx', models.PositiveSmallIntegerField()),
                ('password', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.applicationpassword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('value_for_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.serviceconfigurationstep')),
            ],
            options={
                'unique_together': {('value_for_step', 'set_idx', 'user')},
            },
        ),
    ]
