# Generated by Django 5.0.7 on 2024-09-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_applicationpassword_service_allow_max_configurations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='allow_max_configurations',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='serviceconfigurationstep',
            name='default',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceconfigurationstep',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='serviceconfigurationstep',
            unique_together={('index', 'service')},
        ),
    ]
