# Generated by Django 5.1.1 on 2024-09-10 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_userserviceconnection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='can_have_application_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userserviceconnection',
            name='application_password',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_connection', to='main.applicationpassword'),
        ),
    ]
