# Generated by Django 5.1.1 on 2024-09-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_service_can_have_application_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='configuration_view_template',
            field=models.TextField(blank=True),
        ),
    ]
