# Generated by Django 5.1.1 on 2024-09-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_service_configuration_view_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='require_2fa_if_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='userserviceconnection',
            unique_together={('user', 'service')},
        ),
    ]
