# Generated by Django 5.1.2 on 2024-11-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_originmigrationtoken_parent_session_sessiontreeedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfigurationstep',
            name='include_in_claims',
            field=models.BooleanField(default=True),
        ),
    ]
