# Generated by Django 5.1.2 on 2025-02-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_originmigrationtoken_parent_session_sessiontreeedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='forward_auth_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='forward_auth_groups',
            field=models.ManyToManyField(blank=True, to='main.group'),
        ),
        migrations.AddField(
            model_name='code',
            name='forward_auth_user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='forward_auth_user_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='service',
            name='allow_expose_forward_auth_headers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='allow_expose_forward_auth_headers_ips',
            field=models.TextField(blank=True),
        ),
    ]
