# Generated by Django 5.1.2 on 2025-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_code_forward_auth_email_code_forward_auth_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='forward_auth_username',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
