# Generated by Django 5.1.2 on 2025-03-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_serviceconfigurationstep_include_in_claims'),
        ('main', '0021_code_forward_auth_username'),
    ]

    operations = [
    ]
