# Generated by Django 5.1.7 on 2025-04-02 17:08

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_merge_20250311_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=64, unique=False, null=True),
        ),
    ]
