# Generated by Django 5.1.7 on 2025-04-02 17:16

from django.db import migrations
import main.models

def wrap_gen_uid(apps, schema_editor):
    UserModel = apps.get_model("main", "User")
    for row in UserModel.objects.all():
        row.uid = main.models.generate_user_id()
        row.save(update_fields=["uid"])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_user_uid'),
    ]

    operations = [
        migrations.RunPython(wrap_gen_uid)
    ]
