# Generated by Django 5.1.7 on 2025-04-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_user_uid_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=64, unique=True, null=False),
        ),
    ]
