# Generated by Django 5.1.7 on 2025-04-10 08:48

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_user_uid_make_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSetting',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=main.models.generate_user_id, max_length=64, unique=True),
        ),
    ]
