# Generated by Django 5.1.7 on 2025-04-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_coresetting_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sso_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.group'),
        ),
    ]
