# Generated by Django 5.1.7 on 2025-06-19 16:15

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_user_sso_groups'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('token', models.CharField(default=main.models.gen_login_link, max_length=128)),
                ('purpose', models.CharField(choices=[('poisson.loginlink.purpose.password_reset', 'Password Reset'), ('poisson.loginlink.purpose.service_login', 'Service Login'), ('poisson.loginlink.purpose.session_login', 'Generic Login tied to session')], max_length=48)),
                ('valid_until', models.DateTimeField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_login_links', to=settings.AUTH_USER_MODEL)),
                ('parent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
