# Generated by Django 5.1.7 on 2025-08-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_loginlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='https',
            field=models.BooleanField(default=True),
        ),
    ]
