# Generated by Django 5.1.7 on 2025-08-24 19:57

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_service_https'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlink',
            name='token',
            field=models.CharField(default=main.models.gen_login_link, max_length=128, unique=True),
        ),
    ]
