# Generated by Django 5.1.7 on 2025-09-11 17:21

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_loginlink_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='uid',
            field=models.CharField(max_length=64, unique=False, null=True),
        ),
    ]
