# Generated by Django 5.1.7 on 2025-09-11 17:21

import main.models
from django.db import migrations

def wrap_gen_uid(apps, schema_editor):
    ServiceModel = apps.get_model("main", "Service")
    for row in ServiceModel.objects.all():
        row.uid = main.models.generate_service_id()
        row.save(update_fields=["uid"])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_service_uid'),
    ]

    operations = [
        migrations.RunPython(wrap_gen_uid)
    ]
