# Generated by Django 5.1.7 on 2025-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_service_uid_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='uid',
            field=models.CharField(max_length=64, unique=True, null=False),
        ),
    ]
