# Generated by Django 5.1.7 on 2025-09-12 15:59

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_service_uid_make_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quirk_use_numeric_pk_as_sub',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='uid',
            field=models.CharField(default=main.models.generate_user_id, max_length=64, unique=True),
        ),
    ]
