# Generated by Django 5.1.7 on 2025-09-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_service_quirk_use_numeric_pk_as_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='quirk_use_numeric_pk_as_sub',
            field=models.BooleanField(default=False),
        ),
    ]
