# Generated by Django 5.1.7 on 2025-04-15 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_webauthn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webauthndevice',
            name='name',
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='backed_up',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='cred_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='device_type',
            field=models.CharField(choices=[('single_device', 'single_device'), ('multi_device', 'multi_device')], default='multi_device', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='icon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='last_seen_sign_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='last_used',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='publicKey',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
