# Generated by Django 5.1.7 on 2025-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_webauthn', '0002_remove_webauthndevice_name_webauthndevice_backed_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthndevice',
            name='name',
            field=models.CharField(default='', help_text='The human-readable name of this device.', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webauthndevice',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
