# Generated by Django 5.1.7 on 2025-04-17 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_webauthn', '0003_webauthndevice_name_alter_webauthndevice_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthndevice',
            name='current_challenge',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webauthndevice',
            name='current_challenge_expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
