# Generated by Django 5.1.7 on 2025-04-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_webauthn', '0005_remove_webauthndevice_pubkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthndevice',
            name='current_challenge',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webauthndevice',
            name='current_challenge_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
