# Generated by Django 5.1.7 on 2025-04-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_webauthn', '0006_alter_webauthndevice_current_challenge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webauthndevice',
            name='credentials',
        ),
    ]
